backend:
  name: github
  repo: Abhinash-Dhar/yours-science-hub
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "notes"
    label: "Notes"
    folder: "content/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
