backend:
  name: git-gateway
  branch: main
  identity_url: "https://dashing-cuchufli-2a4f9b.netlify.app/.netlify/identity"

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "notes"
    label: "Notes"
    folder: "content/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Category", name: "category", widget: "string", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
